auto: true
server: true
url: http://blog.stealth35.com
paginate: 3
menu_items: 
    - { title: Home,      link: / }
    - { title: Downloads, link: https://github.com/stealth35/stealth35.github.com/downloads }
    - { title: PEAR,      link: /pear }
    - { title: GitHub,    link: https://github.com/stealth35 }
    - { title: Tweeter,   link: http://twitter.com/stealth35 }